### ISSUE TITLE
implementing versioning

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/glitter#14]
## Problem

Before v1, let's version. This way we can make updates and slowly roll out changes to apps when we need to, using an established versioned system.

## Solution
- implement https://semver.org/ versioning
- v1 should be when someone can use layouts and styles in their app for: 
  - forms
  - header
  - footer
  - padding 
  - margin
  - *note* this means we are still in pre-release! (3/13/2018)
- Use a Ruby Gem for distributing our assets (sass, css, javascript, react) to our apps
- Update Wiki about how to bump versions, implement a CHANGELOG
- [x] Make a future issue to add webpack or alternative to build locally as well

**Comment by isometimescode** [comment]
Also something to think about: https://phraseapp.com/blog/posts/sharing-assets-between-rails/

**Comment by isometimescode** [comment]
@kaitlynhova and I talked, and decided that we will focus on #17 because using a normal frontend standard like Webpack will support more options in the future (and not limit us to Rails). Versioned releases will happen there as well.
